### ISSUE TITLE
Addon sometimes fail to play NRK videos

### ISSUE THREAD

**Issue by xiphias256** [tamland/xbmc-addon-nrk#37]
This is what I get in the kodi.log
---
07:49:20 T:135065600  NOTICE: -->Python Interpreter Initialized<--
07:49:22 T:135065600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.HTTPError'>
                                            Error Contents: 503 Server Error: Backend fetch failed
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.nrk/default.py", line 228, in <module>
                                                plugin.run()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.routing/lib/routing.py", line 98, in run
                                                self._dispatch(path)
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.routing/lib/routing.py", line 109, in _dispatch
                                                view_func(**kwargs)
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.nrk/default.py", line 203, in play
                                                urls = nrktv.program(video_id).media_urls
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.nrk/nrktv_mobile.py", line 167, in program
                                                return Program.from_response(_get('/programs/%s' % program_id))
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.video.nrk/nrktv_mobile.py", line 142, in _get
                                                r.raise_for_status()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib/requests/models.py", line 851, in raise_for_status
                                                raise HTTPError(http_error_msg, response=self)
                                            HTTPError: 503 Server Error: Backend fetch failed
                                            -->End of Python script error report<--
07:49:22 T:42258432   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.nrk/play/koif24006614]
---

This is on a ATV2 with kodi 14.2

**Comment by tamland** [comment]
"Server Error". Dessverre ikke noe vi kan gjøre noe med.

**Comment by xiphias256** [comment]
Oj, sløft av meg å ikke se det før jeg sende det inn! :-/  Men kunne det
bli gjort om til en feature-request og få skriptet til å gi en mer
forklarende feilmelding, i steden for det generiske "script error, see log
for more info"?

Mvh,
Finn
