### ISSUE TITLE
412 precondition failed when accessing the API

### ISSUE THREAD

**Issue by asmundg** [tamland/xbmc-addon-nrk#38]
```

17:50:48 T:139680204953344   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.HTTPError'>
                                            Error Contents: 412 Client Error: Precondition Failed for url: http://tvapi.nrk.no/v1/channels
                                            Traceback (most recent call last):
                                              File "/home/asmundg/.kodi/addons/plugin.video.nrk/default.py", line 235, in <module>
                                                plugin.run()
                                              File "/home/asmundg/.kodi/addons/script.module.routing/lib/routing.py", line 109, in run
                                                self._dispatch(path)
                                              File "/home/asmundg/.kodi/addons/script.module.routing/lib/routing.py", line 120, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/asmundg/.kodi/addons/plugin.video.nrk/default.py", line 49, in live
                                                for ch in nrktv.channels():
                                              File "/home/asmundg/.kodi/addons/plugin.video.nrk/nrktv.py", line 181, in channels
                                                return [Channel.from_response(item) for item in _get('/channels')]
                                              File "/home/asmundg/.kodi/addons/plugin.video.nrk/nrktv.py", line 152, in _get
                                                r.raise_for_status()
                                              File "/home/asmundg/.kodi/addons/script.module.requests/lib/requests/models.py", line 840, in raise_for_status
                                                raise HTTPError(http_error_msg, response=self)
                                            HTTPError: 412 Client Error: Precondition Failed for url: http://tvapi.nrk.no/v1/channels
                                            -->End of Python script error report<--
17:50:48 T:139680996165632   ERROR: GetDirectory - Error getting plugin://plugin.video.nrk/live
17:50:48 T:139680996165632   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nrk/live) failed
```

**Comment by esnalabu** [comment]
I tried rolling back to v4.5.4 (6fea12f77143ce51654db2f7f7663f9599b920b3) with no success. More changes in the API?
