### ISSUE TITLE
Cryptography lib OpenSSL Error

### ISSUE THREAD

**Issue by eN0Rm** [tamland/xbmc-addon-nrk#42]
Here's the error message from kodi.log

` T:140510660392704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'cryptography.exceptions.InternalError'>
                                            Error Contents: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLError(code=621174887L, l
ib=37, func=102, reason=103), _OpenSSLError(code=621215847L, lib=37, func=112, reason=103), _OpenSSLError(code=638279812L, lib=38, func=182, reason=132), _OpenSSLError(code=637968500L, lib=38, func=106, reason=116)])
                                            Traceback (most recent call last):
                                              File "/home/expology/.kodi/addons/plugin.video.nrk/main.py", line 18, in <module>
                                                import addon
                                              File "/home/expology/.kodi/addons/plugin.video.nrk/addon.py", line 27, in <module>
                                                import nrktv
                                              File "/home/expology/.kodi/addons/plugin.video.nrk/nrktv.py", line 21, in <module>
                                                from requests import Session
                                              File "/home/expology/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 52, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/home/expology/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
                                                from cryptography.hazmat.backends.openssl import backend as openssl_backend
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
                                                from cryptography.hazmat.backends.openssl.backend import backend
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 2299, in <module>
                                                backend = Backend()
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 716, in __init__
                                                self.activate_osrandom_engine()
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 738, in activate_osrandom_engine
                                                self.openssl_assert(e != self._ffi.NULL)
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/backend.py", line 719, in openssl_assert
                                                return binding._openssl_assert(self._lib, ok)
                                              File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 43, in _openssl_assert
                                                errors
                                            InternalError: Unknown OpenSSL error. Please file an issue at https://github.com/pyca/cryptography/issues with information on how to reproduce this. ([_OpenSSLError(code=621174887L, lib=37, func=102, reason=103), _OpenSSLError(code=621215847L, lib=37, func=112, reason=103), _OpenSSLError(code=638279812L, lib=38, func=182, reason=132), _OpenSSLError(code=637968500L, lib=38, func=106, reason=116)])
                                            -->End of Python script error report<--
07:18:26 T:140512834922816   ERROR: GetDirectory - Error getting plugin://plugin.video.nrk/live
07:18:26 T:140512834922816   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nrk/live) failed
`

**Comment by tamland** [comment]
Du må oppdatere OpenSSL/pycrypto ol. på systemet ditt.
