### ISSUE TITLE
Warns of memory leaks

### ISSUE THREAD

**Issue by kjetilk** [tamland/xbmc-addon-nrk#55]
Seems there is something wrong with NRK right now, the API returns a `503`. I guess that's not the add-on's fault, but the warning I had was a bit ominous, so, I figure I'd report it:
```
22:45:13.262 T:1199567776   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.HTTPError'>
                                            Error Contents: 503 Server Error: Backend fetch failed for url: https://psapi.nrk.no/medium/tv/popularprograms/week?apiKey=d1381d92278a47c09066460f2522a67d&maxnumber=15
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nrk/main.py", line 21, in <module>
                                                addon.run()
                                              File "/storage/.kodi/addons/plugin.video.nrk/addon.py", line 265, in run
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.nrk/addon.py", line 190, in popular
                                                programs = nrktv.popular_programs()
                                              File "/storage/.kodi/addons/plugin.video.nrk/nrktv.py", line 219, in popular_programs
                                                '&maxnumber=15')]
                                              File "/storage/.kodi/addons/plugin.video.nrk/nrktv.py", line 189, in _get
                                                r.raise_for_status()
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/models.py", line 940, in raise_for_status
                                                raise HTTPError(http_error_msg, response=self)
                                            HTTPError: 503 Server Error: Backend fetch failed for url: https://psapi.nrk.no/medium/tv/popularprograms/week?apiKey=d1381d92278a47c09066460f2522a67d&maxnumber=15
                                            -->End of Python script error report<--
```

**Comment by solbu** [comment]
I did a test, and opened the link that fails.
It is the backend server behind the API varnish server that have problems.

===
«Error 503 Backend fetch failed
Backend fetch failed
Guru Meditation:
XID: 184552840
Varnish cache server»

**Comment by solbu** [comment]
The live streams works however, so all is not lost just yet. :-)

**Comment by solbu** [comment]
And a day or so later all was fine.
My guess is that the lightning storm took down some systems at NRK.

**Comment by solbu** [comment]
Recommend closing this issue.

**Comment by kjetilk** [comment]
Oh, but this bug report wasn't about the problem at NRK's side, that is not something that can be fixed in Kodi, but about the warning of a memory leak, in case that is something that might occur also when NRK is running fine.

**Comment by solbu** [comment]
That warning comes in every addon crash. I have yet to see an addon crash og have error messages, without seeing that memory leak warning.
