### ISSUE TITLE
Plugin is unable to show fetch subtitles.

### ISSUE THREAD

**Issue by fredrikhr** [tamland/xbmc-addon-nrk#59]
When attempting to watch yesterday's daily news program (`Dagsrevyen`) the plugin failed to obtain the subtitles for the video.

The following error was logged to the log file:

``` txt
2020-07-05 13:30:14.618 T:3011125264  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.nrk/play/NNFA02070420
2020-07-05 13:30:14.788 T:2387161968   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.ConnectionError'>
                                            Error Contents: HTTPConnectionPool(host='v8.psapi.nrk.no', port=80): Max retries exceeded with url: /programs/NNFA02070420/subtitles/tt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa8679950>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nrk/main.py", line 21, in <module>
                                                addon.run()
                                              File "/storage/.kodi/addons/plugin.video.nrk/addon.py", line 265, in run
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.nrk/addon.py", line 247, in play
                                                subtitle = subs.get_subtitles(video_id)
                                              File "/storage/.kodi/addons/plugin.video.nrk/subs.py", line 26, in get_subtitles
                                                html = requests.get("http://v8.psapi.nrk.no/programs/%s/subtitles/tt" % video_id).text
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 75, in get
                                                return request('get', url, params=params, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 60, in request
                                                return session.request(method=method, url=url, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 533, in request
                                                resp = self.send(prep, **send_kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 646, in send
                                                r = adapter.send(request, **kwargs)
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 516, in send
                                                raise ConnectionError(e, request=request)
                                            ConnectionError: HTTPConnectionPool(host='v8.psapi.nrk.no', port=80): Max retries exceeded with url: /programs/NNFA02070420/subtitles/tt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xa8679950>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
                                            -->End of Python script error report<--
```

Kodi reports that my installed version of the Plugin is version `4.7.0`.

**Comment by solbu** [comment]
The server «v8.psapi.nrk.no» is not reachable. That is the reason, which the plugin can do nothing about.
I tried opening the page in Firefox, and also pinged and tracerouted the server. It is not available.

My advice is to disable subtitles for the time being.

**Comment by fredrikhr** [comment]
@solbu That does not really help me much, does it? The whole purpose with this issue is to keep it here to make subtitles work!

And for something like the news, I really need the subtitles, as international news aren't dubbed on NRK, meaning I'd have to understand Arabic, French, Spanish, etc. to understand what is said when someone abroad is interviewed.

**Comment by smalahove** [comment]
@fredrikhr: If a server at NRK is unreachable, perhaps address your frustration at them instead?

**Comment by fredrikhr** [comment]
Sorry, I am not expressing frustration, I just wanted to point out that the [suggested workaround](https://github.com/tamland/xbmc-addon-nrk/issues/59#issuecomment-653914594) isn't helpful and explain why disabling subtitles isn't ideal.

@smalahove well the plugin hasn't been updated since 2018, so my guess is that NRK just moved the service to another URL. I have not yet finished investigating what is the correct URL would be, but that will probably be the fix for this issue.

**Comment by fosspill** [comment]
Is there anything a newbie could do to help research this issue - and find the correct url?

**Comment by fosspill** [comment]
I found "nrk-download" which successfully downloads subtitles. 
By following the nrk-download code it seems like this is a valid way for doing it, for most shows. (This is based on the NNFA02070420 id provided in the first issue)
https://undertekst.nrk.no/prod/NNFA02/07/NNFA02070420/TTV/NNFA02070420.vtt
