### ISSUE TITLE
Some categories fail to display their content

### ISSUE THREAD

**Issue by CaptainTyphoo** [tamland/xbmc-addon-nrk#63]
Some categories fail to display their content. If you click on them, a message in the top right corner appears, saying that an error occurred. This is the stack trace printed to the log file when clicking on "Show og underholdning":

```
2021-02-28 12:10:10.842 T:139894374704896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'requests.exceptions.HTTPError'>
                                            Error Contents: 404 Client Error: Not Found for url: https://psapi.nrk.no/medium/tv/categories/show-og-underholdning/indexelements?apiKey=d1381d92278a47c09066460f2522a67d
                                            Traceback (most recent call last):
                                              File "/home/vagrant/.kodi/addons/plugin.video.nrk/main.py", line 21, in <module>
                                                addon.run()
                                              File "/home/vagrant/.kodi/addons/plugin.video.nrk/addon.py", line 265, in run
                                                plugin.run()
                                              File "/home/vagrant/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/vagrant/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/vagrant/.kodi/addons/plugin.video.nrk/addon.py", line 203, in category
                                                items = nrktv.programs(category_id)
                                              File "/home/vagrant/.kodi/addons/plugin.video.nrk/nrktv.py", line 274, in programs
                                                items = _get('/medium/tv/categories/%s/indexelements' % category_id)
                                              File "/home/vagrant/.kodi/addons/plugin.video.nrk/nrktv.py", line 189, in _get
                                                r.raise_for_status()
                                              File "/home/vagrant/.kodi/addons/script.module.requests/lib/requests/models.py", line 940, in raise_for_status
                                                raise HTTPError(http_error_msg, response=self)
                                            HTTPError: 404 Client Error: Not Found for url: https://psapi.nrk.no/medium/tv/categories/show-og-underholdning/indexelements?apiKey=d1381d92278a47c09066460f2522a67d
                                            -->End of Python script error report<--
2021-02-28 12:10:10.868 T:139894587074304   ERROR: GetDirectory - Error getting plugin://plugin.video.nrk/category/show-og-underholdning
2021-02-28 12:10:10.877 T:139894888686016   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nrk/category/show-og-underholdning) failed
```

These categories do not work:
- Dyr
- Hjem, interiør og design
- Klima og miljø
- Konkurranser og reality-TV
- Kropp og helse
- Kunst og scene
- Mat
- Reise
- Show og underholdning
- Teknologi og vitenskap

These categories work:
- Barn
- Dokumentar
- Familie
- Humor
- Litteratur (is empty)
- Musikk (is empty)
- Natur
- NRK-arkivet
- Nyheter
- Samisk
- Serier
- Sport
- Synstolk (is empty)
- Tegnspråk

(The API is showing different categories depending on whether you use https://psapi.nrk.no/medium/tv/categories or https://psapi.nrk.no/medium/tv/categories/.)

**Comment by CaptainTyphoo** [comment]
I had a look at the PSAPI Documentation (http://psapi-documentation.azurewebsites.net/documentation/) and it's not really clear to me which URL is the correct one. Once this has been clarified, I will create a pull request.

**Comment by solbu** [comment]
I have noticed the same problem, and by some brain fart it didn't occur to me to look for a log stack trace and post it.
